// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waesbetptdfvwtzqjros.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZXNiZXRwdGRmdnd0enFqcm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjU4MTIsImV4cCI6MjA3MzQwMTgxMn0.BG1EpyLwzGxrMPPk4NyWA14aNWbOuapSyVpo6uYJmZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});